generateAliasAsModel: true

################
## C# options ##
################
packageName: Calcasa.Api.V1
packageVersion: 1.4.0
licenseId: Apache-2.0
packageCopyright: Copyright 2025 Calcasa B.V.
packageDescription: API client for the Calcasa Public API.
packageCompany: Calcasa
packageAuthors: Calcasa
packageTitle: Calcasa API Client
packageReleaseNotes: Add callback update and read endpoints and models.
gitHost: github.com
gitUserId: calcasa
gitRepoId: api-csharp
homepage: https://calcasa.nl
excludeTests: true
httpUserAgent: Calcasa .NET Api Client/1.4.0
dateTimeFormat: yyyy'-'MM'-'dd'T'HH':'mm':'ssZ
equatable: true
hideGenerationTimestamp: true
useNewtonsoft: true
useSwashbuckle: false
isLibrary: true
buildTarget: program
operationIsAsync: true # we postprocess this, to retain the CancellationToken but remove the async keyword
operationModifier: abstract
operationResultTask: true
nullableReferenceTypes: true
useFrameworkReference: true
enumNameSuffix: ''
enumValueSuffix: ''
useDefaultRouting: true
aspnetCoreVersion: 8.0
pocoModels: true
modelClassModifier: partial
classModifier: abstract
