generateAliasAsModel: true

####################
## Python options ##
####################
# invokerPackage: calcasa.api.apis
# projectName: calcasa-api
# packageName: calcasa.api
pythonAttrNoneIfUnset: true
packageName: calcasa.api
packageVersion: 1.4.0
licenseInfo: Apache-2.0
licenseId: Apache-2.0
infoName: Calcasa B.V.
infoEmail: info@calcasa.nl
packageUrl: https://github.com/calcasa/api-python
packageCopyright: Copyright 2025 Calcasa B.V.
appDescription: API client for the Calcasa Public API.
excludeTests: true
httpUserAgent: Calcasa Python Api Client/1.4.0
